### ISSUE TITLE
Create a list of features for the first version

### ISSUE THREAD

**Issue by bkielbasa** [go-bdd/vscode-extension#5]
Let's start with MVP. We should think about features which are critical and start with them first.

**Comment by mirogta** [comment]
Looking here for inspiration:
https://specflow.org/documentation/Visual-Studio-Integration/

I'm thinking about 3 categories - what can we do with:
* feature files
* steps
* source code (under test)

I have 2 candidates to work on first:
1. A simple "Generate steps file" command from an active feature file - just with a simple that if a steps file exists, it would just give a warning and do nothing. This would give a head-start for people to use GoBDD with cucumber knowledge but without knowing GoBDD structure.
2. Navigate from steps in feature files to their implementation and vice versa, via a command and also a suitable keyboard shortcut.

WDYT?

**Comment by bkielbasa** [comment]
yeah, that sounds good :)
